### ISSUE TITLE
occasional ZeroDivisionError: float division by zero error

### ISSUE THREAD

**Issue by strowger** [jdhorne/pycarwings2#10]
i'm occasionally seeing this:

```
Traceback (most recent call last):
 File "/data/hm/bin/leaf.py", line 35, in <module>
   battery_status = l.get_status_from_update(result_key)
 File "/usr/lib/python2.7/site-packages/pycarwings2/pycarwings2.py", line 224, in get_status_from_update
   return CarwingsBatteryStatusResponse(response)
 File "/usr/lib/python2.7/site-packages/pycarwings2/responses.py", line 244, in __init__
   self.battery_percent = 100 * float(status["batteryDegradation"]) / float(status["batteryCapacity"])
ZeroDivisionError: float division by zero
```

generally an immediate retry succeeds.

**Comment by filcole** [comment]
Thanks for the report. This is fixed in commit https://github.com/filcole/pycarwings2/commit/54043da04dc710b22f67b02d4f3b87df69560ad0 the dev branch of my [fork of pycarwings2](https://github.com/filcole/pycarwings2). It will be included in the next release.
