### ISSUE TITLE
KeyError: BatteryStatusRecords

### ISSUE THREAD

**Issue by dico** [jdhorne/pycarwings2#18]
Can't get the example-script to work. Any suggestions?

`# /usr/bin/python ./get-leaf-info.py
Prepare Session
Login...
get_latest_battery_status
Traceback (most recent call last):
  File "./get-leaf-info.py", line 28, in <module>
    leaf_info = l.get_latest_battery_status()
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 372, in get_latest_battery_status
    return CarwingsLatestBatteryStatusResponse(response)
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/responses.py", line 508, in __init__
    CarwingsResponse.__init__(self, status["BatteryStatusRecords"])
KeyError: 'BatteryStatusRecords'`

**Comment by dico** [comment]
Never mind :-) Started working after I logged out/in on the Carwings app, and then updated the status in the app.

**Comment by davehun** [comment]
getting the same error
