### ISSUE TITLE
location update not working (Canada)

### ISSUE THREAD

**Issue by johnty** [jdhorne/pycarwings2#32]
Thanks for the library! All the examples seem to work (region: NCI/canada), except for the get-leaf-location example, which returns a ``` error -5256: [MyCarFinder] API call error```

Is this possibly due to the API not available in Canada? Also, just for curiosity's sake, do any other regions allow you to find the location of the vehicle?

**Comment by SchuldtOH** [comment]
Same for me in Germany. I figured out, it is because of the missing gdc_user_id. This is empty in my case:

Traceback (most recent call last):
  File "get-leaf-location.py", line 31, in <module>
    result_key = l.request_location()
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 415, in request_location
    "UserId": self.session.gdc_user_id, # this userid is the 'gdc' userid
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 101, in _request_with_retry
    ret = self._request(endpoint, params)
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 141, in _request
    raise CarwingsError
pycarwings2.pycarwings2.CarwingsError

**Comment by karora** [comment]
Same for me in Ireland.  I have a late 2015 Tekna, but I can't see what the gdc_user_id and password would be for?

Is there someone for whom this *does* work who could say whether gdc_user_id & password in their response matches the login userID and password, or are they something completely different, and if they are, where can we get them?

**Comment by filcole** [comment]
get-leaf-location.py for me, based in the UK using [my fork of pycarwings2](https://github.com/filcole/pycarwings2)

POST /api_v181217_NE/gdc/UserLoginRequest.php 

returns ....  "gdcUserId":"","gdcPassword":"",  ....  
it does return "dcmId":"xxxxxxxxxx".
