### ISSUE TITLE
change in URL for UK users?

### ISSUE THREAD

**Issue by irekzielinski** [jdhorne/pycarwings2#35]
Hi guys. Started to get this error recently (used to work 99% of time, not always fails):

```
DEBUG:pycarwings2.pycarwings2:invoking carwings API: https://gdcportalgw.its-mo.com/gworchest_160803A/gdc/InitialApp.php
DEBUG:pycarwings2.pycarwings2:params: {
   "RegionCode": "NE",
   "custom_sessionid": "",
   "initial_app_strings": "redacted_out",
   "lg": "en-US"
}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gdcportalgw.its-mo.com
DEBUG:urllib3.connectionpool:https://gdcportalgw.its-mo.com:443 "POST /gworchest_160803A/gdc/InitialApp.php HTTP/1.1" 404 234
DEBUG:pycarwings2.pycarwings2:Response HTTP Status Code: 404
DEBUG:pycarwings2.pycarwings2:Response HTTP Response Body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /gworchest_160803A/gdc/InitialApp.php was not found on this server.</p>
</body></html>

Traceback (most recent call last):
  File "get-leaf-battery.py", line 33, in <module>
    l = s.get_leaf()
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 189, in get_leaf
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 151, in connect
    "lg": "en-US",
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 134, in _request
    j = json.loads(response.content)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Looks like the URL changed?
Anyone seeing this?

Cheers,
Irek

**Comment by gym22** [comment]
Looks like there is a new API:
https://gist.github.com/BenWoodford/141ca350445e994e69a70aabfb6db942
Somebody has already implemented it:
https://github.com/gboudreau/nissan-connect-php/commit/297d47f69b1060b32ea324d62afa7839f16ba654

Maybe the old one was turned off over the weekend.

Gyula

**Comment by irekzielinski** [comment]
oh snap!
hope new API works in Europe - code looks like US oriented....

**Comment by rduivenvoorde** [comment]
@irekzielinski my scripts broke too...  but the official app is still working with me. Not sure how to find out which api/server that it is using now...

I also tried BenWoodfords calls (from the comments), but get an

```
{"errorMessage":"Authentication Failure","errorCode":910}
```
using NE as country

@jdhorne what do you think?

**Comment by gym22** [comment]
The US and EU apps are now completely different.
https://play.google.com/store/apps/details?id=com.digitas.android.nissan.carwings
https://play.google.com/store/apps/details?id=com.aqsmartphone.android.nissan

I think the new API is for the US app only.

**Comment by gym22** [comment]
got the new url from the eu app:  https://gdcportalgw.its-mo.com/api_v180117_NE/gdc

replace BASE_URL in pycarwings2.py and it works.

**Comment by BenWoodford** [comment]
@gym22 thanks for that info!

Indeed the new API is only in the US (and probably Japan?), the old API is the only one we have in the EU.

**Comment by rduivenvoorde** [comment]
@gym22 THANKS! Created a PR, url needs to end with a '/' : 
```
BASE_URL = "https://gdcportalgw.its-mo.com/api_v180117_NE/gdc/"
```
Works like a charm \o/

**Comment by glynhudson** [comment]
Good spot. I wonder if this is to do with the new European GDPR? European user data is now hopefully being kept in Europe. Hopefully this will improve reliability.

**Comment by tarcus69** [comment]
Looks like it's changed again today: [https://twitter.com/NissanEV_UK/status/1076200864044515328?s=15](https://twitter.com/NissanEV_UK/status/1076200864044515328?s=15)

I'm getting a 404 not found on the standard UK API now.

**Comment by Wobbley** [comment]
I can verify the same, do we know what the new URL is?

**Comment by gym22** [comment]
https://gdcportalgw.its-mo.com/api_v181217_NE/ <https://gdcportalgw.its-mo.com/api_v181217_NE/>

**Comment by BenWoodford** [comment]
Oh, I used this one:

https://github.com/BenWoodford/pycarwings2/commit/1170caf2482b9fbf275e867f55472479197a4660

**Comment by tarcus69** [comment]
@BenWoodford working fine for me with that new URL.

**Comment by rduivenvoorde** [comment]
For me (NL here) the https://gdcportalgw.its-mo.com/api_v181217_NE/, but @BenWoodford's one: https://gdcportalgw.its-mo.com/gworchest_160803EC/gdc/  is.

Update: when adding "/gdc/" to the first url BOTH are working for me: https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/

Thanks All, for this work!

**Comment by joeshaw** [comment]
See also the discussion on https://github.com/BenWoodford/pycarwings2/commit/1170caf2482b9fbf275e867f55472479197a4660

**Comment by filcole** [comment]
I've got a working version of this library and published it to PyPi.  

It uses the same URL as mentioned above https://github.com/jdhorne/pycarwings2/issues/35#issuecomment-449659792 and also by [dartcarwings](https://gitlab.com/tobiaswkjeldsen/dartcarwings/blob/d6b0b1c3f3e84356db3bce744a40d172ae817f09/lib/src/carwings_session.dart)
